_wandb:
    value:
        cli_version: 0.23.1
        e:
            jzlskzkfhujurminp7uboomn1fq19vh4:
                codePath: checkwd.py
                codePathLocal: checkwd.py
                email: nganha4216@gmail.com
                executable: /mnt/disk1/miniconda3/envs/tindl/bin/python
                git:
                    commit: 936e38ff19269115cc19466808092c147fc9b3e6
                    remote: https://github.com/hungtrab/DL20251_benchmarks_cv_models
                host: vaipe-Z790-UD-AX
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /mnt/disk3/tinvt/DL20251_benchmarks_cv_models/checkwd.py
                python: CPython 3.10.12
                root: /mnt/disk3/tinvt/DL20251_benchmarks_cv_models
                startedAt: "2025-12-19T15:51:48.286488Z"
                writerId: jzlskzkfhujurminp7uboomn1fq19vh4
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
            "4": 3.10.12
            "5": 0.23.1
            "8":
                - 2
            "12": 0.23.1
            "13": linux-x86_64
